newrelic/nr1-catalog

.gitmodules

Adds nr1-deployment-analyzer nerdpack.

Sync up with experimental

---

docs/docs/process.js

docs: typo fix.

---

.github/pull_request_template.md

- me (@tangollama)
- immediate deployment
- Screenshot revision by @jbeveland27

feat: upgrade nr1-groundskeeper to 0.9.0

---

.github/pull_request_template.md
.gitmodules

- Approvers: TBD
- 5/1/2020
- Disable or enable E2M rules 
- Check Metric cardinality as you create your E2M rule
- Filter E2M rules
@jbeveland27 after you approve, I want to be sure we get a formal approval from the PM or PMM before we merge.

feat: add nr1-metrics-aggregator

---

.gitmodules

- Approvers: TBD
- 5/1/2020
- Disable or enable E2M rules 
- Check Metric cardinality as you create your E2M rule
- Filter E2M rules
@tangollama I re-opened the addition of this app to the catalog with a new PR after merging (#33) too quickly (#34 undid those changes). Now we can get formal approval from PM or PMM and let the automation run like normal.
@jsgithub1 Let's reference this PR going forward. When you have time, please review and sign off for us to merge and add this to the New Relic One Catalog.

feat: add nr1-metrics-aggregator to New Relic One Catalog

---

.gitmodules

- Provide the **GitHub handle** for the final Approver of this Nerdpack in your Pull Request. *Note: this is the person who will need to provide explicit sign off for the change ahead of deployment.*
- If known, what is the requested date for the deployment of this functionality? *Note: this information is regarded as a courtesy. Neither New Relic nor the **nr1-catalog maintainer team** are under any obligation to meet this request. It simply provides a useful target for completion.*
- Major feature #1
- Major feature #2
*Note: The rest of this template is a checklist and guide for ensuring that your pull request is swiftly and consistently approved.*
Validate that the following are …

feat: Adding NR1-Account-Maturity to nr1-catalog

---

.gitmodules

- Provide the **GitHub handle** for the final Approver of this Nerdpack in your Pull Request. *Note: this is the person who will need to provide explicit sign off for the change ahead of deployment.*
- If known, what is the requested date for the deployment of this functionality? *Note: this information is regarded as a courtesy. Neither New Relic nor the **nr1-catalog maintainer team** are under any obligation to meet this request. It simply provides a useful target for completion.*
- Major feature #1
- Major feature #2
*Note: The rest of this template is a checklist and guide for ensuring that your pull request is swiftly and consistently approved.*
Validate that the following are …

Adding Donor Analyzer 

---

.gitmodules

- Approver: TBD
- Target date: On or before 7/30/2020
- Advance your NRQL skills through a series of levels of learning
- Control the data you see from your accounts with a simple Account Picker
- Copy or open the sample query in Chart Builder
- Resume from the last level/lesson the user was on

feat: Adding nr1-learn-nrql to nr1-catalog at v1.0.0

---

.gitmodules

- me @Kav91 
- Completely refactored & redeveloped Nerdpack to replace Flex Manger

feat: updating nr1-flex-manager to nr1-integrations-manager 1.5.1

---

.gitmodules

- Final approver:  goldenplec
- Target date: 8/7/2020
- Instructional design review changes

feat: Update nr1-learn-nrql to v1.1.0

---

.gitmodules

feat: Add nr1-alerts-los-migrator at v1.2.2

---

.gitmodules

- jbeveland27
- fix broken community link in config.json

feat(nr1-alerts-los-migrator): update to v1.2.5

---

.gitmodules
README.md

This PR removes the sub module for the nr1-donor-analyzer app so it be removed from the catalog repo. 
also read me update 📖

Submodule removal

---

.gitmodules

- Provide the **GitHub handle** for the final Approver of this Nerdpack in your Pull Request. *Note: this is the person who will need to provide explicit sign off for the change ahead of deployment.*
- If known, what is the requested date for the deployment of this functionality? *Note: this information is regarded as a courtesy. Neither New Relic nor the **nr1-catalog maintainer team** are under any obligation to meet this request. It simply provides a useful target for completion.*
- Major feature #1
- Major feature #2
*Note: The rest of this template is a checklist and guide for ensuring that your pull request is swiftly and consistently approved.*
Validate that the following are …

chore: revert

---

.gitmodules

- Provide the **GitHub handle** for the final Approver of this Nerdpack in your Pull Request. *Note: this is the person who will need to provide explicit sign off for the change ahead of deployment.*
- If known, what is the requested date for the deployment of this functionality? *Note: this information is regarded as a courtesy. Neither New Relic nor the **nr1-catalog maintainer team** are under any obligation to meet this request. It simply provides a useful target for completion.*
**Target Date: 8/5/2021**
Adding a new Public nerdpack - kentik network telemetry visualizations
*Note: The rest of this template is a checklist and guide for ensuring that your pull request is swiftly and …

feat: Adding nr1-kentik-network-monitoring to catalog

---

globals.json

This PR removes the reference of the app from globals.json

chore: removes reference from globals.json

---

.github/workflows/catalog-pr.yml
.github/workflows/check-for-deprecations.yml

feat: update to node 16

---

.gitmodules

feat: Add nr-labs-pathpoint at version v2.0.1

---

.github/workflows/catalog-pr.yml

Reverts newrelic/nr1-catalog#736

Revert "switch to https from ssh"

---

.github/workflows/release.yml

echo output of eu release for debugging

output eu release for debugging
